=== Thermax1/Java-and-Web-Projects/Java-Testing/Java-XML-DTD-Schema/videogames.dtd
<!ELEMENT collection (game+)> <!-- The + means that child element game must occur one or more times in the collection element-->
<!ELEMENT game (title, genre, format, price, console)>
<!ELEMENT title (#PCDATA)> <!-- #PCDATA means that the text content should be parsed and processed by XML parser-->
<!ELEMENT genre (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT console (#PCDATA)>
<!ATTLIST game id CDATA #REQUIRED>

=== Thermax1/Java-and-Web-Projects/Java-Testing/Java-XML-DTD-Schema/videogames.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This XML document will be used for a video game collection -->
<!DOCTYPE collection SYSTEM "./videogames.dtd">
<collection>
    <game id="1">
        <title>Xenoblade Chronicles</title>
        <genre>JRPG</genre>
        <format>Physical</format>
        <price>$55</price>
        <console>Wii</console>
    </game>
    <game id="2">
        <title>Horzion Zero Dawn</title>
        <genre>Action</genre>
        <format>Digital</format>
        <price>$60</price>
        <console>PS4</console>
    </game>
    <game id="3">
        <title>Uncharted</title>
        <genre>Adventure</genre>
        <format>Physical</format>
        <price>$10</price>
        <console>PS3</console>
    </game>
    <game id="4">
        <title>Fallout-1</title>
        <genre>RPG</genre>
        <format>Digital</format>
        <price>$5</price>
        <console>PC</console>
    </game>
</collection>
